### PR TITLE
fix(test): force test failure

### PR DESCRIPTION
**Pull request by oscard0m**
# Description

Assure 'test' Check Run is always executed and `fails`/`succeeds` accordingly to the results of its dependency jobs.

- Example commit with all tests passing ✅: c4a2c50e7eb30baa6b3fb54c75e3c31429c591ed
- Example commit with tests failing 🔴: 8d93278aa268be6706f97c973a17d3d05cbac53f

---
# Context
When using `job.needs`, [by default only runs when the dependency jobs succeed](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds). If one or more of them fail, the dependent job is **skipped**

### CODE REVIEW

**Comment by oscard0m** [comment]
@gr2m @wolfy1339 @timrogers I think I found the issue. I'm surprised this did not appear before.

What do you think about my solution proposal? Do you agree with solving this in the context of https://github.com/octokit/.github/pull/13?

**Comment by timrogers** [comment]
What is your proposed solution? I'm not sure I understand from this PR.

**Comment by timrogers** [comment]
Sounds reasonable to me 🤷🏻

**Comment by wolfy1339** [comment]
> What do you think about my solution proposal? Do you agree with solving this in the context of https://github.com/octokit/.github/pull/13?

This will work for now, until we sort out the reusable workflows

**Comment by oscard0m** [comment]
> This will work for now, until we sort out the reusable workflows

@wolfy1339  
Do you mean you want me to apply this change to all our repositories until https://github.com/octokit/.github/pull/13 is addressed?

**Comment by wolfy1339** [comment]
> > This will work for now, until we sort out the reusable workflows
> 
> @wolfy1339 Do you mean you want me to apply this change to all our repositories until [octokit/.github#13](https://github.com/octokit/.github/pull/13) is addressed?

Yes. That would be great

**Review by gr2m — APPROVED** [review]
Change looks good, I think we did something similar in a different project.

**Review by wolfy1339 — APPROVED** [review]

**Comment by gr2m** [comment]
Here is the discussion we had in @semantic-release, we arrived at the same conclusion, but did not yet implement the change

https://github.com/semantic-release/semantic-release/pull/2229

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
